# Generated by Django 5.2.6 on 2025-09-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=200)),
                ('room_capacity', models.IntegerField()),
                ('room_hours', models.IntegerField()),
                ('status', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
