# Generated by Django 5.2.6 on 2025-09-11 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_room_room_capacity_alter_room_room_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_hours',
            field=models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(24)),
        ),
    ]
