name: Testing

on:
  push:
    branches: [ testing ] 
  pull_request:
    branches: [ testing ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.7'

    - name: Install dependencies
      run: |
        cd classroom_booking
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run migrations
      run: |
        cd classroom_booking
        python manage.py migrate

    - name: Run tests with coverage
      run: |
        cd classroom_booking
        coverage run manage.py test
        coverage report -m

    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
      if: success()
